<% from "build.inc.yml" import workflow, workflow_dispatch -%>
name: Build Test and Publish a Testing Release

on:
  <<- workflow_dispatch() >>

jobs:
  <<- workflow(targets, publications, servers, subdist="testing", publish_all=True) ->>
